AllCops:
  Exclude:
    - "db/**"
    - bin/bundle
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

require:
  - rubocop-rails

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
